export default [
    {"id":0,"title":"title1",
        "brief":"brief1",
        "content":"congfhghfhtent ",
        "author":{"id":1,"username":"admin1","password":"admin1"},
        "changeDate":1546020000000,
        "uri":"ff1"},
    {"id":1,"title":"title2",
        "brief":"brief2",
        "content":"content ",
        "author":{"id":1,"username":"admin1","password":"admin1"},
        "changeDate":1546020000000,
        "uri":"ff2"},
    {"id":2,"title":"title3",
        "brief":"brief3",
        "content":"content ",
        "author":{"id":1,"username":"admin1","password":"admin1"},
        "changeDate":1546020000000,
        "uri":"ff3"},
    {"id":3,"title":"title4",
        "brief":"brief4",
        "content":"content ",
        "author":{"id":1,"username":"admin1","password":"admin1"},
        "changeDate":1546020000000,
        "uri":"ff4"}
]